NAME,ISACTIVE,FAMILY,COLOR__C,INVENTORY_USED__C,INITIAL_INVENTORY__C,COST__C
Anastasia Painted Blue,TRUE,Chrysanthemums,Blue,,120,0.25
Barcelona,TRUE,Carnations,Orange,,200,0.5
Agropoli,TRUE,Alstromeria,Purple,,160,0.5
Anastasia Painted Green,TRUE,Chrysanthemums,Green,,50,0.75
Abracadabra,TRUE,Carnations,Green,,130,0.75
Tripolium pannonicum,TRUE,Asters,White,,200,1.2
Pink Protea,TRUE,Exotic Blooms,Pink,,200,1
Leopard Orchid,TRUE,Exotic Blooms,Red,,200,0.8
Yellow Solidago,TRUE,Fillers,Yellow,,200,0.25
Lopez,TRUE,Gladiolas,Yellow,,200,0.25
Camellia Foliage,TRUE,Foliages,Green,,200,0.5
Elegans,TRUE,Gypsophila,White,,200,0.25
Fastigiata,TRUE,Gypsophila,White,,200,0.25
Lilium CASA Blanca,TRUE,Lilies,White,,200,0.5
Lilium Silk Road,TRUE,Lilies,Red,,200,0.75
Lilium Commander In Chief,TRUE,Lilies,Red,,200,0.75
Sinuatum,TRUE,Limonium,Purple,,200,0.75
Humile,TRUE,Limonium,White,,200,0.75
Moth,TRUE,Orchids,Pink,,200,1
Red Rose Preservation,TRUE,Preserved,Red,,200,1
Nitida,TRUE,Proteas,Yellow,,200,1
Petal Flower Rose,TRUE,Roses,Other,,200,0.5
Red Rose,TRUE,Roses,Red,,200,0.5
Yellow Rose,TRUE,Roses,Yellow,,200,0.5
